from __future__ import annotations

from DILIGENT.app.constants import (
    DOCS_PATH,
    RAG_CHUNK_OVERLAP,
    RAG_CHUNK_SIZE,
    RAG_EMBEDDING_BACKEND,
    RAG_HF_EMBEDDING_MODEL,
    RAG_OLLAMA_BASE_URL,
    RAG_OLLAMA_EMBEDDING_MODEL,
    RAG_RESET_VECTOR_COLLECTION,
    RAG_VECTOR_INDEX_METRIC,
    RAG_VECTOR_INDEX_TYPE,
    VECTOR_COLLECTION_NAME,
    VECTOR_DB_PATH,
)
