[package]
name = "diligent-desktop"
version = "2.2.0"
description = "DILIGENT desktop shell"
authors = ["DILIGENT"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.3.0", features = [] }

[dependencies]
tauri = { version = "=2.6.2", features = [] }

[patch.crates-io]
cookie = { path = "vendor/cookie-0.18.1" }
tauri = { path = "vendor/tauri-2.6.2" }
