from __future__ import annotations

from common.utils.languages import (
    SUPPORTED_REPORT_LANGUAGES,
    resolve_supported_language_code,
)
from domain.clinical.entities import DrugRucamAssessment


_EVIDENCE_QUALITY_LABELS = {
    "direct_match_with_excerpt": {
        "en": "direct local match with supporting excerpt",
        "it": "corrispondenza locale diretta con estratto di supporto",
        "es": "coincidencia local directa con extracto de apoyo",
        "fr": "correspondance locale directe avec extrait justificatif",
        "de": "direkter lokaler Treffer mit unterstützendem Auszug",
        "pt": "correspondência local direta com excerto de suporte",
    },
}

_LIMITATION_LABELS = {
    "onset anchor not score-eligible": {
        "en": "the onset anchor is not eligible for scoring",
        "it": "l'ancoraggio temporale dell'esordio non è idoneo al punteggio",
        "es": "el anclaje temporal del inicio no es apto para puntuación",
        "fr": "le repère temporel de début n'est pas admissible au score",
        "de": "der zeitliche Beginn ist nicht für die Bewertung geeignet",
        "pt": "o marco temporal de início não é elegível para pontuação",
    },
}

_PHRASES = {
    "en": {
        "case_summary": "Case summary",
        "extracted_sections": "Extracted sections",
        "anamnesis": "Anamnesis",
        "therapy": "Therapy",
        "laboratory_history": "Laboratory history",
        "hepatic_injury_pattern": "Hepatic injury pattern",
        "drug_assessments": "Drug assessments",
        "bibliography": "Bibliography",
        "conclusion": "Conclusion",
        "provided": "provided",
        "calculated": "calculated",
        "not_calculated_insufficient_data": "not calculated because of insufficient data",
        "rucam_source_reported": "RUCAM score reported directly from trusted source.",
        "rucam_structured_score": "Structured RUCAM score: {score} ({category}).",
        "rucam_not_calculated": "RUCAM not calculated due to insufficient criteria-level evidence.",
        "rucam_insufficient_data": "Insufficient criteria-level evidence for RUCAM.",
        "rucam_score_source": "Score source",
        "rucam_causality_category": "Causality category",
        "rucam_limitations": "RUCAM limitations",
        "livertox_missing": "No matching LiverTox record available.",
        "livertox_ambiguous": "Ambiguous LiverTox match.",
        "unresolved_mentions": "Unresolved Drug Mentions",
        "evidence_quality": "Evidence quality",
        "report_section_summary": "Global Synthesis and Clinical Recommendations",
        "report_section_per_drug": "Per-drug assessment",
        "unnamed_drug": "Unnamed drug",
        "candidate_matches": "Candidate matches: {candidates}.",
        "manual_curation": "Manual curation is required before causality assessment.",
        "no_matching_record": "No matching drug record found in the local knowledge base.",
        "matched_no_excerpt": "Matched drug record found, but no local LiverTox excerpt is available.",
        "deterministic_section_unavailable": "Could not produce a deterministic matched-drug section.",
        "report_label": "Report",
        "bibliography_source": "Bibliography source",
        "clinical_commentary": "Clinical commentary",
        "commentary_evidence_match": "Local evidence match: {quality}; matched record: {target}.",
        "commentary_evidence_warnings": "Evidence warnings: {warnings}.",
        "commentary_no_evidence_warnings": "No evidence warnings were identified.",
        "commentary_rucam_not_assessable": "RUCAM causality is not assessable from the available criteria.",
        "commentary_limitations": "Main limitations: {limitations}.",
        "commentary_review_required": "Clinical review is required.",
        "commentary_no_review_required": "No additional structured-claim review is required.",
        "none": "None",
        "not_available": "not available",
        "unknown": "unknown",
        "narrative_fallback": "Final report generated in fallback mode because clinical synthesis was unavailable. Manual specialist review is required.",
    },
    "it": {
        "case_summary": "Sintesi del caso",
        "extracted_sections": "Sezioni estratte",
        "anamnesis": "Anamnesi",
        "therapy": "Terapia",
        "laboratory_history": "Storia laboratoristica",
        "hepatic_injury_pattern": "Pattern di danno epatico",
        "drug_assessments": "Valutazioni dei farmaci",
        "bibliography": "Bibliografia",
        "conclusion": "Conclusione",
        "provided": "fornito",
        "calculated": "calcolato",
        "not_calculated_insufficient_data": "non calcolato per dati insufficienti",
        "rucam_source_reported": "Punteggio RUCAM riportato direttamente da fonte attendibile.",
        "rucam_structured_score": "Punteggio RUCAM strutturato: {score} ({category}).",
        "rucam_not_calculated": "RUCAM non calcolato per evidenze cliniche insufficienti a livello di criteri.",
        "rucam_insufficient_data": "Dati insufficienti per il calcolo RUCAM.",
        "rucam_score_source": "Fonte del punteggio",
        "rucam_causality_category": "Categoria di causalità",
        "rucam_limitations": "Limiti RUCAM",
        "livertox_missing": "Nessun record LiverTox corrispondente disponibile.",
        "livertox_ambiguous": "Corrispondenza LiverTox ambigua.",
        "unresolved_mentions": "Menzioni Farmaco Non Risolte",
        "evidence_quality": "Qualità dell'evidenza",
        "report_section_summary": "Sintesi Globale e Raccomandazioni Cliniche",
        "report_section_per_drug": "Valutazione per farmaco",
        "unnamed_drug": "Farmaco senza nome",
        "candidate_matches": "Corrispondenze candidate: {candidates}.",
        "manual_curation": "È richiesta una revisione manuale prima della valutazione di causalità.",
        "no_matching_record": "Nessun record del farmaco corrispondente trovato nella base di conoscenza locale.",
        "matched_no_excerpt": "Record del farmaco trovato, ma nessun estratto LiverTox locale disponibile.",
        "deterministic_section_unavailable": "Impossibile produrre una sezione deterministica per il farmaco associato.",
        "report_label": "Report",
        "bibliography_source": "Fonte bibliografica",
        "clinical_commentary": "Commento clinico",
        "commentary_evidence_match": "Corrispondenza con evidenza locale: {quality}; record associato: {target}.",
        "commentary_evidence_warnings": "Avvisi sull'evidenza: {warnings}.",
        "commentary_no_evidence_warnings": "Non sono stati identificati avvisi sull'evidenza.",
        "commentary_rucam_not_assessable": "La causalità RUCAM non è valutabile con i criteri disponibili.",
        "commentary_limitations": "Limiti principali: {limitations}.",
        "commentary_review_required": "È richiesta una revisione clinica.",
        "commentary_no_review_required": "Non è richiesta ulteriore revisione delle affermazioni strutturate.",
        "not_available": "non disponibile",
        "unknown": "sconosciuta",
        "narrative_fallback": "Report finale generato in modalità di fallback perché la sintesi clinica non era disponibile. È richiesta revisione specialistica manuale.",
    },
    "es": {
        "case_summary": "Resumen del caso",
        "extracted_sections": "Secciones extraídas",
        "anamnesis": "Anamnesis",
        "therapy": "Terapia",
        "laboratory_history": "Historia de laboratorio",
        "hepatic_injury_pattern": "Patrón de lesión hepática",
        "drug_assessments": "Evaluaciones de fármacos",
        "bibliography": "Bibliografía",
        "conclusion": "Conclusión",
        "provided": "proporcionado",
        "calculated": "calculado",
        "not_calculated_insufficient_data": "no calculado por datos insuficientes",
        "rucam_source_reported": "Puntuación RUCAM informada directamente por una fuente confiable.",
        "rucam_structured_score": "Puntuación RUCAM estructurada: {score} ({category}).",
        "rucam_not_calculated": "RUCAM no calculado por evidencia insuficiente a nivel de criterios.",
        "rucam_insufficient_data": "Evidencia insuficiente para calcular RUCAM.",
        "rucam_score_source": "Fuente de la puntuación",
        "rucam_causality_category": "Categoría de causalidad",
        "rucam_limitations": "Limitaciones de RUCAM",
        "livertox_missing": "No hay registro LiverTox coincidente disponible.",
        "livertox_ambiguous": "Coincidencia LiverTox ambigua.",
        "unresolved_mentions": "Menciones de Fármacos No Resueltas",
        "evidence_quality": "Calidad de la evidencia",
        "report_section_summary": "Síntesis Global y Recomendaciones Clínicas",
        "report_section_per_drug": "Evaluación por fármaco",
        "unnamed_drug": "Fármaco sin nombre",
        "candidate_matches": "Coincidencias candidatas: {candidates}.",
        "manual_curation": "Se requiere revisión manual antes de la evaluación de causalidad.",
        "no_matching_record": "No se encontró un registro de fármaco coincidente en la base local.",
        "matched_no_excerpt": "Se encontró registro del fármaco, pero no hay extracto local de LiverTox.",
        "deterministic_section_unavailable": "No fue posible generar una sección determinista del fármaco.",
        "report_label": "Informe",
        "bibliography_source": "Fuente bibliográfica",
        "clinical_commentary": "Comentario clínico",
        "commentary_evidence_match": "Coincidencia con evidencia local: {quality}; registro asociado: {target}.",
        "commentary_evidence_warnings": "Advertencias de evidencia: {warnings}.",
        "commentary_no_evidence_warnings": "No se identificaron advertencias de evidencia.",
        "commentary_rucam_not_assessable": "La causalidad RUCAM no puede evaluarse con los criterios disponibles.",
        "commentary_limitations": "Limitaciones principales: {limitations}.",
        "commentary_review_required": "Se requiere revisión clínica.",
        "commentary_no_review_required": "No se requiere revisión adicional de afirmaciones estructuradas.",
        "not_available": "no disponible",
        "unknown": "desconocida",
        "narrative_fallback": "Informe final generado en modo de respaldo porque la síntesis clínica no estaba disponible. Se requiere revisión manual por especialista.",
    },
    "fr": {
        "case_summary": "Résumé du cas",
        "extracted_sections": "Sections extraites",
        "anamnesis": "Anamnèse",
        "therapy": "Thérapie",
        "laboratory_history": "Historique de laboratoire",
        "hepatic_injury_pattern": "Profil de lésion hépatique",
        "drug_assessments": "Évaluations des médicaments",
        "bibliography": "Bibliographie",
        "conclusion": "Conclusion",
        "provided": "fourni",
        "calculated": "calculé",
        "not_calculated_insufficient_data": "non calculé faute de données suffisantes",
        "rucam_source_reported": "Score RUCAM rapporté directement depuis une source fiable.",
        "rucam_structured_score": "Score RUCAM structuré : {score} ({category}).",
        "rucam_not_calculated": "RUCAM non calculé faute de preuves suffisantes au niveau des critères.",
        "rucam_insufficient_data": "Données insuffisantes pour calculer le RUCAM.",
        "rucam_score_source": "Source du score",
        "rucam_causality_category": "Catégorie de causalité",
        "rucam_limitations": "Limites du RUCAM",
        "livertox_missing": "Aucun enregistrement LiverTox correspondant disponible.",
        "livertox_ambiguous": "Correspondance LiverTox ambiguë.",
        "unresolved_mentions": "Mentions de Médicaments Non Résolues",
        "evidence_quality": "Qualité des preuves",
        "report_section_summary": "Synthèse Globale et Recommandations Cliniques",
        "report_section_per_drug": "Évaluation par médicament",
        "unnamed_drug": "Médicament sans nom",
        "candidate_matches": "Correspondances candidates : {candidates}.",
        "manual_curation": "Une revue manuelle est requise avant l'évaluation de causalité.",
        "no_matching_record": "Aucun enregistrement médicamenteux correspondant dans la base locale.",
        "matched_no_excerpt": "Enregistrement du médicament trouvé, mais aucun extrait local LiverTox n'est disponible.",
        "deterministic_section_unavailable": "Impossible de produire une section déterministe pour le médicament associé.",
        "report_label": "Rapport",
        "bibliography_source": "Source bibliographique",
        "clinical_commentary": "Commentaire clinique",
        "commentary_evidence_match": "Correspondance avec les preuves locales : {quality} ; dossier associé : {target}.",
        "commentary_evidence_warnings": "Avertissements sur les preuves : {warnings}.",
        "commentary_no_evidence_warnings": "Aucun avertissement sur les preuves n'a été identifié.",
        "commentary_rucam_not_assessable": "La causalité RUCAM ne peut pas être évaluée avec les critères disponibles.",
        "commentary_limitations": "Principales limites : {limitations}.",
        "commentary_review_required": "Une revue clinique est requise.",
        "commentary_no_review_required": "Aucune revue supplémentaire des affirmations structurées n'est requise.",
        "not_available": "non disponible",
        "unknown": "inconnue",
        "narrative_fallback": "Rapport final généré en mode de repli car la synthèse clinique n'était pas disponible. Une revue spécialisée manuelle est requise.",
    },
    "de": {
        "case_summary": "Fallzusammenfassung",
        "extracted_sections": "Extrahierte Abschnitte",
        "anamnesis": "Anamnese",
        "therapy": "Therapie",
        "laboratory_history": "Laborverlauf",
        "hepatic_injury_pattern": "Muster der Leberschädigung",
        "drug_assessments": "Arzneimittelbewertungen",
        "bibliography": "Literatur",
        "conclusion": "Schlussfolgerung",
        "provided": "bereitgestellt",
        "calculated": "berechnet",
        "not_calculated_insufficient_data": "wegen unzureichender Daten nicht berechnet",
        "rucam_source_reported": "RUCAM-Wert direkt aus vertrauenswürdiger Quelle übernommen.",
        "rucam_structured_score": "Strukturierter RUCAM-Score: {score} ({category}).",
        "rucam_not_calculated": "RUCAM wurde wegen unzureichender kriterienspezifischer Evidenz nicht berechnet.",
        "rucam_insufficient_data": "Unzureichende Evidenz für die RUCAM-Berechnung.",
        "rucam_score_source": "Score-Quelle",
        "rucam_causality_category": "Kausalitätskategorie",
        "rucam_limitations": "RUCAM-Einschränkungen",
        "livertox_missing": "Kein passender LiverTox-Eintrag verfügbar.",
        "livertox_ambiguous": "Mehrdeutige LiverTox-Zuordnung.",
        "unresolved_mentions": "Nicht Aufgelöste Arzneimittel-Nennungen",
        "evidence_quality": "Evidenzqualität",
        "report_section_summary": "Globale Synthese und Klinische Empfehlungen",
        "report_section_per_drug": "Arzneimittelbezogene Bewertung",
        "unnamed_drug": "Unbenanntes Arzneimittel",
        "candidate_matches": "Mögliche Treffer: {candidates}.",
        "manual_curation": "Vor der Kausalitätsbewertung ist eine manuelle Prüfung erforderlich.",
        "no_matching_record": "Kein passender Arzneimitteleintrag in der lokalen Wissensbasis gefunden.",
        "matched_no_excerpt": "Arzneimitteleintrag gefunden, aber kein lokaler LiverTox-Auszug verfügbar.",
        "deterministic_section_unavailable": "Ein deterministischer Abschnitt zum zugeordneten Arzneimittel konnte nicht erstellt werden.",
        "report_label": "Bericht",
        "bibliography_source": "Bibliografiequelle",
        "clinical_commentary": "Klinischer Kommentar",
        "commentary_evidence_match": "Abgleich mit lokaler Evidenz: {quality}; zugeordneter Eintrag: {target}.",
        "commentary_evidence_warnings": "Evidenzwarnungen: {warnings}.",
        "commentary_no_evidence_warnings": "Es wurden keine Evidenzwarnungen festgestellt.",
        "commentary_rucam_not_assessable": "Die RUCAM-Kausalität ist anhand der verfügbaren Kriterien nicht beurteilbar.",
        "commentary_limitations": "Wesentliche Einschränkungen: {limitations}.",
        "commentary_review_required": "Eine klinische Prüfung ist erforderlich.",
        "commentary_no_review_required": "Keine zusätzliche Prüfung strukturierter Aussagen erforderlich.",
        "not_available": "nicht verfügbar",
        "unknown": "unbekannt",
        "narrative_fallback": "Abschlussbericht im Fallback-Modus erstellt, weil die klinische Synthese nicht verfügbar war. Eine manuelle fachärztliche Prüfung ist erforderlich.",
    },
    "pt": {
        "case_summary": "Resumo do caso",
        "extracted_sections": "Seções extraídas",
        "anamnesis": "Anamnese",
        "therapy": "Terapia",
        "laboratory_history": "Histórico laboratorial",
        "hepatic_injury_pattern": "Padrão de lesão hepática",
        "drug_assessments": "Avaliações de fármacos",
        "bibliography": "Bibliografia",
        "conclusion": "Conclusão",
        "provided": "fornecido",
        "calculated": "calculado",
        "not_calculated_insufficient_data": "não calculado por dados insuficientes",
        "rucam_source_reported": "Pontuação RUCAM informada diretamente por fonte confiável.",
        "rucam_structured_score": "Pontuação RUCAM estruturada: {score} ({category}).",
        "rucam_not_calculated": "RUCAM não calculado por evidência insuficiente em nível de critérios.",
        "rucam_insufficient_data": "Evidência insuficiente para cálculo do RUCAM.",
        "rucam_score_source": "Fonte da pontuação",
        "rucam_causality_category": "Categoria de causalidade",
        "rucam_limitations": "Limitações do RUCAM",
        "livertox_missing": "Nenhum registro LiverTox correspondente disponível.",
        "livertox_ambiguous": "Correspondência LiverTox ambígua.",
        "unresolved_mentions": "Menções de Fármacos Não Resolvidas",
        "evidence_quality": "Qualidade da evidência",
        "report_section_summary": "Síntese Global e Recomendações Clínicas",
        "report_section_per_drug": "Avaliação por fármaco",
        "unnamed_drug": "Fármaco sem nome",
        "candidate_matches": "Correspondências candidatas: {candidates}.",
        "manual_curation": "É necessária curadoria manual antes da avaliação de causalidade.",
        "no_matching_record": "Nenhum registro de fármaco correspondente foi encontrado na base local.",
        "matched_no_excerpt": "Registro do fármaco encontrado, mas sem excerto local do LiverTox.",
        "deterministic_section_unavailable": "Não foi possível produzir uma seção determinística para o fármaco associado.",
        "report_label": "Relatório",
        "bibliography_source": "Fonte bibliográfica",
        "clinical_commentary": "Comentário clínico",
        "commentary_evidence_match": "Correspondência com evidência local: {quality}; registro associado: {target}.",
        "commentary_evidence_warnings": "Avisos de evidência: {warnings}.",
        "commentary_no_evidence_warnings": "Nenhum aviso de evidência foi identificado.",
        "commentary_rucam_not_assessable": "A causalidade RUCAM não pode ser avaliada com os critérios disponíveis.",
        "commentary_limitations": "Principais limitações: {limitations}.",
        "commentary_review_required": "É necessária revisão clínica.",
        "commentary_no_review_required": "Não é necessária revisão adicional das afirmações estruturadas.",
        "not_available": "não disponível",
        "unknown": "desconhecida",
        "narrative_fallback": "Relatório final gerado em modo de fallback porque a síntese clínica não estava disponível. É necessária revisão manual por especialista.",
    },
}

###############################################################################
def resolve_report_language(code: str | None) -> str:
    resolved = resolve_supported_language_code(code)
    return resolved if resolved in SUPPORTED_REPORT_LANGUAGES else "en"

###############################################################################
def phrase(key: str, language: str, **values: object) -> str:
    lang = resolve_report_language(language)
    table = _PHRASES.get(lang, _PHRASES["en"])
    if key not in table:
        raise KeyError(f"Missing phrase key: {key}")
    return table[key].format(**values)

###############################################################################
def evidence_quality_label(value: str, language: str) -> str:
    lang = resolve_report_language(language)
    labels = _EVIDENCE_QUALITY_LABELS.get((value or "").strip())
    return labels.get(lang, labels["en"]) if labels else value

###############################################################################
def limitation_label(value: str, language: str) -> str:
    lang = resolve_report_language(language)
    labels = _LIMITATION_LABELS.get((value or "").strip().casefold())
    return labels.get(lang, labels["en"]) if labels else value

###############################################################################
def rucam_summary_text(assessment: DrugRucamAssessment, language: str) -> str:
    lang = resolve_report_language(language)
    if assessment.calculation_method == "source_reported":
        return phrase("rucam_source_reported", lang)
    if assessment.total_score is None:
        return phrase("rucam_not_calculated", lang)
    return phrase(
        "rucam_structured_score",
        lang,
        score=assessment.total_score,
        category=assessment.causality_category,
    )

###############################################################################
def report_heading(key: str, language: str) -> str:
    return phrase(key, language)

###############################################################################
def requires_language_repair(text: str, expected_language: str) -> bool:
    lang = resolve_report_language(expected_language)
    if lang == "en":
        return False
    lower = (text or "").lower()
    return "estimated rucam" in lower or "confidence" in lower or "limitations" in lower
